// commitlint.config.cjs
/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "chore",
        "revert",
        "release",
      ],
    ],
    "scope-enum": [
      1,
      "always",
      [
        "shared",
        "web",
        "parser",
        "pricing",
        "comparison",
        "llm",
        "worker",
        "graph-schema",
        "pricing-types",
        "llm-types",
        "deps",
        "ci",
        "release",
        "hooks",
        "docker",
      ],
    ],
    "subject-case": [2, "always", "lower-case"],
    "subject-full-stop": [2, "never", "."],
    "subject-max-length": [2, "always", 72],
    "subject-min-length": [2, "always", 10],
    "header-max-length": [2, "always", 100],
    "body-max-line-length": [0],
  },
};
