import {
  ChangeAction,
  CloudProvider,
  ResourceLayer,
  type GraphModel,
} from "@terraform-viz/graph-schema";

/**
 * Rich demo plan showcasing all five change actions (+ Create, ~ Update,
 * ± Replace, − Delete, = No-op) across every layer with realistic resource
 * attributes and a dense dependency graph.
 */
export const DEMO_PLAN: GraphModel = {
  id: "demo-plan-v2",
  terraformVersion: "1.7.5",
  createdAt: "2026-04-24T10:00:00.000Z",
  nodes: [
    // ═══════════════════════════════════════════════════════════ NETWORK ══════
    {
      id: "aws_vpc.main",
      address: "aws_vpc.main",
      type: "aws_vpc",
      name: "main",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        cidr_block: "10.0.0.0/16",
        enable_dns_support: true,
        enable_dns_hostnames: true,
        tags: { Name: "prod-vpc", Env: "production", Owner: "platform-team" },
      },
    },
    {
      id: "aws_subnet.public_a",
      address: "aws_subnet.public_a",
      type: "aws_subnet",
      name: "public_a",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        cidr_block: "10.0.1.0/24",
        availability_zone: "us-east-1a",
        map_public_ip_on_launch: true,
        tags: { Name: "prod-public-a", Tier: "public" },
      },
    },
    {
      id: "aws_subnet.public_b",
      address: "aws_subnet.public_b",
      type: "aws_subnet",
      name: "public_b",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        cidr_block: "10.0.2.0/24",
        availability_zone: "us-east-1b",
        map_public_ip_on_launch: true,
        tags: { Name: "prod-public-b", Tier: "public" },
      },
    },
    {
      id: "aws_subnet.private_a",
      address: "aws_subnet.private_a",
      type: "aws_subnet",
      name: "private_a",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        cidr_block: "10.0.10.0/24",
        availability_zone: "us-east-1a",
        map_public_ip_on_launch: false,
        tags: { Name: "prod-private-a", Tier: "private" },
      },
    },
    {
      id: "aws_security_group.web",
      address: "aws_security_group.web",
      type: "aws_security_group",
      name: "web",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: {
        description: "Allow HTTP/HTTPS inbound",
        ingress: [
          { from_port: 443, to_port: 443, protocol: "tcp", cidr_blocks: ["0.0.0.0/0"] },
          { from_port: 80, to_port: 80, protocol: "tcp", cidr_blocks: ["0.0.0.0/0"] },
        ],
        egress: [{ from_port: 0, to_port: 0, protocol: "-1", cidr_blocks: ["0.0.0.0/0"] }],
      },
    },
    {
      id: "aws_security_group.db",
      address: "aws_security_group.db",
      type: "aws_security_group",
      name: "db",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        description: "Allow Postgres from app tier only",
        ingress: [{ from_port: 5432, to_port: 5432, protocol: "tcp", source_security_group: "sg-0a1b2c3d" }],
      },
    },
    {
      id: "aws_route_table.old_nat",
      address: "aws_route_table.old_nat",
      type: "aws_route_table",
      name: "old_nat",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: {
        vpc_id: "vpc-0a1b2c3d4e5f",
        route: [{ cidr_block: "0.0.0.0/0", nat_gateway_id: "nat-deprecated" }],
        tags: { Name: "old-nat-rt", Deprecated: "true" },
      },
    },

    // ═══════════════════════════════════════════════════════════ COMPUTE ══════
    {
      id: "aws_lb.main",
      address: "aws_lb.main",
      type: "aws_lb",
      name: "main",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        load_balancer_type: "application",
        internal: false,
        idle_timeout: 60,
        enable_deletion_protection: true,
        tags: { Name: "prod-alb", Tier: "public" },
      },
    },
    {
      id: "aws_instance.bastion",
      address: "aws_instance.bastion",
      type: "aws_instance",
      name: "bastion",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.REPLACE,
      moduleAddress: null,
      attributes: {
        instance_type: "t3.micro",
        ami: "ami-0c02fb55956c7d316",
        key_name: "prod-bastion-key",
        associate_public_ip_address: true,
        root_block_device: { volume_size: 20, volume_type: "gp3", encrypted: true },
        tags: { Name: "prod-bastion", Role: "bastion" },
      },
    },
    {
      id: "aws_autoscaling_group.app",
      address: "aws_autoscaling_group.app",
      type: "aws_autoscaling_group",
      name: "app",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: {
        min_size: 2,
        max_size: 12,
        desired_capacity: 4,
        health_check_type: "ELB",
        health_check_grace_period: 300,
        tags: [{ key: "Name", value: "prod-app-asg", propagate_at_launch: true }],
      },
    },
    {
      id: "aws_lambda_function.processor",
      address: "aws_lambda_function.processor",
      type: "aws_lambda_function",
      name: "processor",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        function_name: "prod-event-processor",
        runtime: "nodejs20.x",
        handler: "index.handler",
        memory_size: 512,
        timeout: 30,
        environment: { variables: { LOG_LEVEL: "info", QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/123456789/prod-events" } },
      },
    },
    {
      id: "aws_instance.worker_old",
      address: "aws_instance.worker_old",
      type: "aws_instance",
      name: "worker_old",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: {
        instance_type: "c5.xlarge",
        ami: "ami-deprecated-2022",
        key_name: "legacy-key",
        tags: { Name: "legacy-worker", Deprecated: "true", MigrationStatus: "replaced-by-lambda" },
      },
    },
    {
      id: "aws_ecs_service.api",
      address: "aws_ecs_service.api",
      type: "aws_ecs_service",
      name: "api",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        cluster: "prod-cluster",
        desired_count: 3,
        launch_type: "FARGATE",
        task_definition: "prod-api:42",
        network_configuration: { subnets: ["subnet-0a1", "subnet-0a2"], assign_public_ip: false },
      },
    },

    // ══════════════════════════════════════════════════════════ DATABASE ══════
    {
      id: "aws_db_instance.postgres",
      address: "aws_db_instance.postgres",
      type: "aws_db_instance",
      name: "postgres",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: {
        engine: "postgres",
        engine_version: "15.4",
        instance_class: "db.t3.large",
        allocated_storage: 200,
        max_allocated_storage: 1000,
        multi_az: true,
        backup_retention_period: 14,
        deletion_protection: true,
        tags: { Name: "prod-postgres", Tier: "database" },
      },
    },
    {
      id: "aws_db_instance.analytics",
      address: "aws_db_instance.analytics",
      type: "aws_db_instance",
      name: "analytics",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.REPLACE,
      moduleAddress: null,
      attributes: {
        engine: "mysql",
        engine_version: "8.0.35",
        instance_class: "db.r6g.large",
        allocated_storage: 500,
        multi_az: false,
        parameter_group_name: "mysql8-prod",
        tags: { Name: "prod-analytics-db", Purpose: "reporting" },
      },
    },
    {
      id: "aws_elasticache_cluster.redis",
      address: "aws_elasticache_cluster.redis",
      type: "aws_elasticache_cluster",
      name: "redis",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        engine: "redis",
        engine_version: "7.0",
        node_type: "cache.t3.small",
        num_cache_nodes: 1,
        tags: { Name: "prod-redis", Purpose: "session-cache" },
      },
    },
    {
      id: "aws_dynamodb_table.sessions",
      address: "aws_dynamodb_table.sessions",
      type: "aws_dynamodb_table",
      name: "sessions",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        name: "prod-sessions",
        billing_mode: "PAY_PER_REQUEST",
        hash_key: "session_id",
        attribute: [{ name: "session_id", type: "S" }],
        ttl: { attribute_name: "expires_at", enabled: true },
        tags: { Name: "prod-sessions", Purpose: "user-sessions" },
      },
    },
    {
      id: "aws_db_instance.legacy_mysql",
      address: "aws_db_instance.legacy_mysql",
      type: "aws_db_instance",
      name: "legacy_mysql",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: {
        engine: "mysql",
        engine_version: "5.7",
        instance_class: "db.t2.medium",
        allocated_storage: 100,
        final_snapshot_identifier: "legacy-mysql-final-snap",
        tags: { Name: "legacy-mysql", Deprecated: "true", DataMigrated: "true" },
      },
    },

    // ═══════════════════════════════════════════════════════════ STORAGE ══════
    {
      id: "aws_s3_bucket.assets",
      address: "aws_s3_bucket.assets",
      type: "aws_s3_bucket",
      name: "assets",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        bucket: "my-app-static-assets-prod",
        versioning: { enabled: true },
        server_side_encryption_configuration: {
          rule: { apply_server_side_encryption_by_default: { sse_algorithm: "AES256" } },
        },
        tags: { Name: "prod-assets", Public: "true" },
      },
    },
    {
      id: "aws_s3_bucket.backups",
      address: "aws_s3_bucket.backups",
      type: "aws_s3_bucket",
      name: "backups",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: {
        bucket: "my-app-db-backups-prod",
        versioning: { enabled: true },
        lifecycle_rule: [{ id: "expire-old", enabled: true, expiration: { days: 90 } }],
        tags: { Name: "prod-backups", Retention: "90d" },
      },
    },
    {
      id: "aws_s3_bucket.logs",
      address: "aws_s3_bucket.logs",
      type: "aws_s3_bucket",
      name: "logs",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: {
        bucket: "my-app-access-logs-2023",
        force_destroy: true,
        tags: { Name: "deprecated-logs", Deprecated: "true", Reason: "consolidated-into-cloudwatch" },
      },
    },
    {
      id: "aws_ebs_volume.data",
      address: "aws_ebs_volume.data",
      type: "aws_ebs_volume",
      name: "data",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        availability_zone: "us-east-1a",
        size: 500,
        type: "gp3",
        iops: 3000,
        throughput: 125,
        encrypted: true,
        tags: { Name: "prod-data-volume" },
      },
    },
    {
      id: "aws_efs_file_system.shared",
      address: "aws_efs_file_system.shared",
      type: "aws_efs_file_system",
      name: "shared",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.REPLACE,
      moduleAddress: null,
      attributes: {
        creation_token: "prod-shared-efs",
        performance_mode: "generalPurpose",
        throughput_mode: "elastic",
        encrypted: true,
        kms_key_id: "arn:aws:kms:us-east-1:123456789:key/abc123",
        tags: { Name: "prod-shared-efs" },
      },
    },

    // ═══════════════════════════════════════════════════════════════ DATA ══════
    {
      id: "aws_kinesis_stream.events",
      address: "aws_kinesis_stream.events",
      type: "aws_kinesis_stream",
      name: "events",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        name: "prod-events",
        shard_count: 4,
        retention_period: 48,
        encryption_type: "KMS",
        tags: { Name: "prod-events-stream" },
      },
    },
    {
      id: "aws_sqs_queue.jobs",
      address: "aws_sqs_queue.jobs",
      type: "aws_sqs_queue",
      name: "jobs",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: {
        name: "prod-background-jobs",
        visibility_timeout_seconds: 300,
        message_retention_seconds: 86400,
        receive_wait_time_seconds: 20,
        redrive_policy: { maxReceiveCount: 5, deadLetterTargetArn: "arn:aws:sqs:us-east-1:123456789:prod-jobs-dlq" },
      },
    },
    {
      id: "aws_sns_topic.alerts",
      address: "aws_sns_topic.alerts",
      type: "aws_sns_topic",
      name: "alerts",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        name: "prod-alerts",
        kms_master_key_id: "alias/aws/sns",
        tags: { Name: "prod-alerts-topic" },
      },
    },
    {
      id: "aws_glue_catalog_database.warehouse",
      address: "aws_glue_catalog_database.warehouse",
      type: "aws_glue_catalog_database",
      name: "warehouse",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: {
        name: "legacy-warehouse",
        description: "Deprecated Glue catalog — migrated to Redshift",
        tags: { Name: "legacy-warehouse", Deprecated: "true" },
      },
    },
    {
      id: "aws_cloudwatch_log_group.app",
      address: "aws_cloudwatch_log_group.app",
      type: "aws_cloudwatch_log_group",
      name: "app",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.REPLACE,
      moduleAddress: null,
      attributes: {
        name: "/prod/app",
        retention_in_days: 90,
        kms_key_id: "arn:aws:kms:us-east-1:123456789:key/logs-key",
        tags: { Name: "prod-app-logs" },
      },
    },
  ],
  edges: [
    // VPC → subnets
    { source: "aws_vpc.main", target: "aws_subnet.public_a" },
    { source: "aws_vpc.main", target: "aws_subnet.public_b" },
    { source: "aws_vpc.main", target: "aws_subnet.private_a" },
    { source: "aws_vpc.main", target: "aws_security_group.web" },
    { source: "aws_vpc.main", target: "aws_security_group.db" },
    // Network → compute
    { source: "aws_subnet.public_a", target: "aws_lb.main" },
    { source: "aws_subnet.public_b", target: "aws_lb.main" },
    { source: "aws_subnet.private_a", target: "aws_autoscaling_group.app" },
    { source: "aws_subnet.private_a", target: "aws_ecs_service.api" },
    { source: "aws_security_group.web", target: "aws_lb.main" },
    { source: "aws_security_group.web", target: "aws_instance.bastion" },
    // Compute internal
    { source: "aws_lb.main", target: "aws_autoscaling_group.app" },
    { source: "aws_lb.main", target: "aws_ecs_service.api" },
    { source: "aws_autoscaling_group.app", target: "aws_lambda_function.processor" },
    // Compute → database
    { source: "aws_ecs_service.api", target: "aws_db_instance.postgres" },
    { source: "aws_ecs_service.api", target: "aws_elasticache_cluster.redis" },
    { source: "aws_ecs_service.api", target: "aws_dynamodb_table.sessions" },
    { source: "aws_autoscaling_group.app", target: "aws_db_instance.analytics" },
    { source: "aws_security_group.db", target: "aws_db_instance.postgres" },
    { source: "aws_security_group.db", target: "aws_db_instance.legacy_mysql" },
    // Compute → storage
    { source: "aws_autoscaling_group.app", target: "aws_s3_bucket.assets" },
    { source: "aws_autoscaling_group.app", target: "aws_ebs_volume.data" },
    { source: "aws_ecs_service.api", target: "aws_efs_file_system.shared" },
    { source: "aws_lb.main", target: "aws_s3_bucket.logs" },
    { source: "aws_db_instance.postgres", target: "aws_s3_bucket.backups" },
    // Compute → data
    { source: "aws_lambda_function.processor", target: "aws_kinesis_stream.events" },
    { source: "aws_lambda_function.processor", target: "aws_sqs_queue.jobs" },
    { source: "aws_ecs_service.api", target: "aws_sns_topic.alerts" },
    { source: "aws_ecs_service.api", target: "aws_cloudwatch_log_group.app" },
    { source: "aws_kinesis_stream.events", target: "aws_glue_catalog_database.warehouse" },
  ],
};

