import {
  ChangeAction,
  CloudProvider,
  ResourceLayer,
  type GraphModel,
} from "@terraform-viz/graph-schema";

/**
 * Enterprise migration plan: EC2 + MySQL → ECS Fargate + Aurora Serverless v2.
 * 30 resources across all 5 layers with all 5 change actions:
 * - NO_OP:    VPC, existing subnets, ALB, app-data S3 (stable infrastructure)
 * - DELETE:   Legacy EC2 instances, MySQL RDS, legacy SG, old EBS volume
 * - CREATE:   ECS cluster + task + service, Aurora + replicas, backups S3, new SG, SQS, alarms
 * - REPLACE:  ElastiCache (engine 6.2 → 7.1, forces recreation)
 * - UPDATE:   ALB listener (swap target group), ASG desired capacity, SNS encryption, CloudWatch dashboard
 */
export const ENTERPRISE_MIGRATION: GraphModel = {
  id: "example-enterprise-migration",
  terraformVersion: "1.7.5",
  createdAt: "2026-04-24T10:00:00.000Z",
  nodes: [
    // ════════════════════════════════════════════════════════ NETWORK ══════
    {
      id: "aws_vpc.prod",
      address: "aws_vpc.prod",
      type: "aws_vpc",
      name: "prod",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { cidr_block: "10.10.0.0/16", enable_dns_support: true, enable_dns_hostnames: true, tags: { Name: "prod-vpc", Env: "prod", Team: "platform", Project: "migration" } },
    },
    {
      id: "aws_subnet.private_a",
      address: "aws_subnet.private_a",
      type: "aws_subnet",
      name: "private_a",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { cidr_block: "10.10.10.0/24", availability_zone: "us-east-1a" },
    },
    {
      id: "aws_subnet.private_b",
      address: "aws_subnet.private_b",
      type: "aws_subnet",
      name: "private_b",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { cidr_block: "10.10.11.0/24", availability_zone: "us-east-1b" },
    },
    {
      id: "aws_subnet.public_a",
      address: "aws_subnet.public_a",
      type: "aws_subnet",
      name: "public_a",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { cidr_block: "10.10.1.0/24", availability_zone: "us-east-1a", map_public_ip_on_launch: true },
    },
    {
      id: "aws_internet_gateway.prod",
      address: "aws_internet_gateway.prod",
      type: "aws_internet_gateway",
      name: "prod",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { tags: { Name: "prod-igw", Env: "prod", Team: "platform", Project: "migration" } },
    },
    {
      id: "aws_security_group.legacy_app",
      address: "aws_security_group.legacy_app",
      type: "aws_security_group",
      name: "legacy_app",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: { name: "legacy-app-sg", description: "Legacy EC2 app security group" },
    },
    {
      id: "aws_security_group.ecs_app",
      address: "aws_security_group.ecs_app",
      type: "aws_security_group",
      name: "ecs_app",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "ecs-app-sg", description: "ECS Fargate container security group" },
    },

    // ════════════════════════════════════════════════════════ COMPUTE ══════
    {
      id: "aws_instance.legacy_web_a",
      address: "aws_instance.legacy_web_a",
      type: "aws_instance",
      name: "legacy_web_a",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: { ami: "ami-0c02fb55956c7d316", instance_type: "t3.medium", tags: { Name: "legacy-web-a", Role: "web", Env: "prod", Team: "legacy", Project: "migration" } },
    },
    {
      id: "aws_instance.legacy_web_b",
      address: "aws_instance.legacy_web_b",
      type: "aws_instance",
      name: "legacy_web_b",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: { ami: "ami-0c02fb55956c7d316", instance_type: "t3.medium", tags: { Name: "legacy-web-b", Role: "web", Env: "prod", Team: "legacy", Project: "migration" } },
    },
    {
      id: "aws_instance.legacy_worker",
      address: "aws_instance.legacy_worker",
      type: "aws_instance",
      name: "legacy_worker",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: { ami: "ami-0c02fb55956c7d316", instance_type: "t3.large", tags: { Name: "legacy-worker", Role: "worker", Env: "prod", Team: "legacy", Project: "migration" } },
    },
    {
      id: "aws_ecs_cluster.prod",
      address: "aws_ecs_cluster.prod",
      type: "aws_ecs_cluster",
      name: "prod",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "prod-cluster", setting: [{ name: "containerInsights", value: "enabled" }], tags: { Env: "prod", Team: "api", Project: "migration" } },
    },
    {
      id: "aws_ecs_task_definition.api",
      address: "aws_ecs_task_definition.api",
      type: "aws_ecs_task_definition",
      name: "api",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { family: "api", cpu: "512", memory: "1024", network_mode: "awsvpc", requires_compatibilities: ["FARGATE"] },
    },
    {
      id: "aws_ecs_service.api",
      address: "aws_ecs_service.api",
      type: "aws_ecs_service",
      name: "api",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "api", desired_count: 2, launch_type: "FARGATE" },
    },
    {
      id: "aws_lb.prod",
      address: "aws_lb.prod",
      type: "aws_lb",
      name: "prod",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { name: "prod-alb", internal: false, load_balancer_type: "application", enable_deletion_protection: true },
    },
    {
      id: "aws_lb_target_group.ecs",
      address: "aws_lb_target_group.ecs",
      type: "aws_lb_target_group",
      name: "ecs",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "ecs-tg", port: 8080, protocol: "HTTP", target_type: "ip", health_check: { path: "/health" } },
    },
    {
      id: "aws_lb_listener.https",
      address: "aws_lb_listener.https",
      type: "aws_lb_listener",
      name: "https",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: { port: 443, protocol: "HTTPS", default_action: { type: "forward", target_group_arn: "ecs-tg" } },
    },
    {
      id: "aws_autoscaling_group.ecs_nodes",
      address: "aws_autoscaling_group.ecs_nodes",
      type: "aws_autoscaling_group",
      name: "ecs_nodes",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: { name: "ecs-nodes", min_size: 1, max_size: 10, desired_capacity: 3 },
    },

    // ════════════════════════════════════════════════════════ DATABASE ══════
    {
      id: "aws_db_instance.mysql",
      address: "aws_db_instance.mysql",
      type: "aws_db_instance",
      name: "mysql",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: { identifier: "prod-mysql", engine: "mysql", engine_version: "5.7.44", instance_class: "db.t3.medium", allocated_storage: 100, multi_az: true },
    },
    {
      id: "aws_rds_cluster.aurora",
      address: "aws_rds_cluster.aurora",
      type: "aws_rds_cluster",
      name: "aurora",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        cluster_identifier: "prod-aurora",
        engine: "aurora-mysql",
        engine_version: "8.0.mysql_aurora.3.05.2",
        database_name: "proddb",
        serverlessv2_scaling_configuration: { min_capacity: 0.5, max_capacity: 16 },
        deletion_protection: true,
        tags: { Env: "prod", Team: "data", Project: "migration" },
      },
    },
    {
      id: "aws_rds_cluster_instance.aurora_primary",
      address: "aws_rds_cluster_instance.aurora_primary",
      type: "aws_rds_cluster_instance",
      name: "aurora_primary",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { cluster_identifier: "prod-aurora", instance_class: "db.serverless", engine: "aurora-mysql" },
    },
    {
      id: "aws_rds_cluster_instance.aurora_replica",
      address: "aws_rds_cluster_instance.aurora_replica",
      type: "aws_rds_cluster_instance",
      name: "aurora_replica",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { cluster_identifier: "prod-aurora", instance_class: "db.serverless", engine: "aurora-mysql" },
    },
    {
      id: "aws_elasticache_replication_group.redis",
      address: "aws_elasticache_replication_group.redis",
      type: "aws_elasticache_replication_group",
      name: "redis",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.REPLACE,
      moduleAddress: null,
      attributes: {
        replication_group_id: "prod-redis",
        description: "Session cache",
        node_type: "cache.r7g.large",
        engine_version: "7.1",
        num_cache_clusters: 2,
        automatic_failover_enabled: true,
        at_rest_encryption_enabled: true,
        transit_encryption_enabled: true,
      },
    },

    // ════════════════════════════════════════════════════════ STORAGE ══════
    {
      id: "aws_s3_bucket.app_data",
      address: "aws_s3_bucket.app_data",
      type: "aws_s3_bucket",
      name: "app_data",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { bucket: "prod-app-data", tags: { Name: "app-data", Env: "prod", Team: "data", Project: "migration" } },
    },
    {
      id: "aws_s3_bucket.backups",
      address: "aws_s3_bucket.backups",
      type: "aws_s3_bucket",
      name: "backups",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { bucket: "prod-backups", tags: { Name: "backups", Env: "prod", Team: "data", Project: "migration" } },
    },
    {
      id: "aws_s3_bucket_versioning.backups",
      address: "aws_s3_bucket_versioning.backups",
      type: "aws_s3_bucket_versioning",
      name: "backups",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { versioning_configuration: { status: "Enabled" } },
    },
    {
      id: "aws_ebs_volume.legacy",
      address: "aws_ebs_volume.legacy",
      type: "aws_ebs_volume",
      name: "legacy",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: { availability_zone: "us-east-1a", size: 200, type: "gp2", encrypted: true, tags: { Name: "legacy-data", Env: "prod", Team: "legacy", Project: "migration" } },
    },

    // ════════════════════════════════════════════════════════════ DATA ══════
    {
      id: "aws_sqs_queue.migration",
      address: "aws_sqs_queue.migration",
      type: "aws_sqs_queue",
      name: "migration",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "data-migration-queue", visibility_timeout_seconds: 300, message_retention_seconds: 1209600, tags: { Env: "prod", Team: "data", Project: "migration" } },
    },
    {
      id: "aws_sns_topic.alerts",
      address: "aws_sns_topic.alerts",
      type: "aws_sns_topic",
      name: "alerts",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: { name: "prod-alerts", kms_master_key_id: "alias/aws/sns", tags: { Env: "prod", Team: "ops", Project: "migration" } },
    },
    {
      id: "aws_cloudwatch_dashboard.prod",
      address: "aws_cloudwatch_dashboard.prod",
      type: "aws_cloudwatch_dashboard",
      name: "prod",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: { dashboard_name: "prod-overview" },
    },
    {
      id: "aws_cloudwatch_metric_alarm.cpu_high",
      address: "aws_cloudwatch_metric_alarm.cpu_high",
      type: "aws_cloudwatch_metric_alarm",
      name: "cpu_high",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        alarm_name: "ecs-cpu-high",
        comparison_operator: "GreaterThanThreshold",
        evaluation_periods: 2,
        metric_name: "CPUUtilization",
        namespace: "AWS/ECS",
        threshold: 80,
      },
    },
  ],
  edges: [
    // Network
    { source: "aws_subnet.private_a",              target: "aws_vpc.prod" },
    { source: "aws_subnet.private_b",              target: "aws_vpc.prod" },
    { source: "aws_subnet.public_a",               target: "aws_vpc.prod" },
    { source: "aws_internet_gateway.prod",         target: "aws_vpc.prod" },
    { source: "aws_security_group.legacy_app",     target: "aws_vpc.prod" },
    { source: "aws_security_group.ecs_app",        target: "aws_vpc.prod" },
    // Compute - legacy
    { source: "aws_instance.legacy_web_a",         target: "aws_security_group.legacy_app" },
    { source: "aws_instance.legacy_web_b",         target: "aws_security_group.legacy_app" },
    { source: "aws_instance.legacy_worker",        target: "aws_security_group.legacy_app" },
    // Compute - ECS
    { source: "aws_ecs_service.api",               target: "aws_ecs_cluster.prod" },
    { source: "aws_ecs_service.api",               target: "aws_ecs_task_definition.api" },
    { source: "aws_ecs_service.api",               target: "aws_security_group.ecs_app" },
    { source: "aws_ecs_service.api",               target: "aws_lb_target_group.ecs" },
    { source: "aws_lb_target_group.ecs",           target: "aws_vpc.prod" },
    { source: "aws_lb.prod",                       target: "aws_subnet.public_a" },
    { source: "aws_lb_listener.https",             target: "aws_lb.prod" },
    { source: "aws_lb_listener.https",             target: "aws_lb_target_group.ecs" },
    { source: "aws_autoscaling_group.ecs_nodes",   target: "aws_subnet.private_a" },
    { source: "aws_autoscaling_group.ecs_nodes",   target: "aws_subnet.private_b" },
    // Database
    { source: "aws_db_instance.mysql",                    target: "aws_subnet.private_a" },
    { source: "aws_rds_cluster.aurora",                   target: "aws_subnet.private_a" },
    { source: "aws_rds_cluster.aurora",                   target: "aws_subnet.private_b" },
    { source: "aws_rds_cluster_instance.aurora_primary",  target: "aws_rds_cluster.aurora" },
    { source: "aws_rds_cluster_instance.aurora_replica",  target: "aws_rds_cluster.aurora" },
    { source: "aws_elasticache_replication_group.redis",  target: "aws_subnet.private_a" },
    { source: "aws_elasticache_replication_group.redis",  target: "aws_subnet.private_b" },
    // Storage
    { source: "aws_s3_bucket_versioning.backups", target: "aws_s3_bucket.backups" },
    // Data
    { source: "aws_cloudwatch_metric_alarm.cpu_high", target: "aws_sns_topic.alerts" },
    { source: "aws_cloudwatch_metric_alarm.cpu_high", target: "aws_ecs_cluster.prod" },
    { source: "aws_sqs_queue.migration",              target: "aws_ecs_service.api" },
  ],
};
