import {
  ChangeAction,
  CloudProvider,
  ResourceLayer,
  type GraphModel,
} from "@terraform-viz/graph-schema";

/**
 * Simple static website plan.
 * S3 → CloudFront CDN → ACM TLS → Route53 DNS.
 * 8 resources, mostly CREATE. Route53 zone is pre-existing (NO_OP).
 * Good for understanding how a basic frontend deployment looks.
 */
export const SIMPLE_STATIC_SITE: GraphModel = {
  id: "example-simple-static-site",
  terraformVersion: "1.7.5",
  createdAt: "2026-04-24T10:00:00.000Z",
  nodes: [
    {
      id: "aws_s3_bucket.website",
      address: "aws_s3_bucket.website",
      type: "aws_s3_bucket",
      name: "website",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { bucket: "my-static-site-prod", tags: { Name: "website", Env: "production", Team: "frontend", Project: "static-site" } },
    },
    {
      id: "aws_s3_bucket_website_configuration.website",
      address: "aws_s3_bucket_website_configuration.website",
      type: "aws_s3_bucket_website_configuration",
      name: "website",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.STORAGE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { index_document: "index.html", error_document: "404.html" },
    },
    {
      id: "aws_cloudfront_origin_access_control.oac",
      address: "aws_cloudfront_origin_access_control.oac",
      type: "aws_cloudfront_origin_access_control",
      name: "oac",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        name: "website-oac",
        origin_access_control_origin_type: "s3",
        signing_behavior: "always",
        signing_protocol: "sigv4",
      },
    },
    {
      id: "aws_acm_certificate.cert",
      address: "aws_acm_certificate.cert",
      type: "aws_acm_certificate",
      name: "cert",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        domain_name: "example.com",
        subject_alternative_names: ["www.example.com"],
        validation_method: "DNS",
      },
    },
    {
      id: "aws_cloudfront_distribution.cdn",
      address: "aws_cloudfront_distribution.cdn",
      type: "aws_cloudfront_distribution",
      name: "cdn",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        enabled: true,
        is_ipv6_enabled: true,
        default_root_object: "index.html",
        price_class: "PriceClass_100",
        aliases: ["example.com", "www.example.com"],
        viewer_certificate: {
          ssl_support_method: "sni-only",
          minimum_protocol_version: "TLSv1.2_2021",
        },
        tags: { Name: "website-cdn" },
      },
    },
    {
      id: "aws_route53_zone.main",
      address: "aws_route53_zone.main",
      type: "aws_route53_zone",
      name: "main",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { name: "example.com", comment: "Managed by Terraform" },
    },
    {
      id: "aws_route53_record.www",
      address: "aws_route53_record.www",
      type: "aws_route53_record",
      name: "www",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "www.example.com", type: "A" },
    },
    {
      id: "aws_route53_record.apex",
      address: "aws_route53_record.apex",
      type: "aws_route53_record",
      name: "apex",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.NETWORK,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "example.com", type: "A" },
    },
  ],
  edges: [
    { source: "aws_cloudfront_distribution.cdn",             target: "aws_s3_bucket.website" },
    { source: "aws_cloudfront_distribution.cdn",             target: "aws_cloudfront_origin_access_control.oac" },
    { source: "aws_cloudfront_distribution.cdn",             target: "aws_acm_certificate.cert" },
    { source: "aws_s3_bucket_website_configuration.website", target: "aws_s3_bucket.website" },
    { source: "aws_route53_record.www",                      target: "aws_route53_zone.main" },
    { source: "aws_route53_record.www",                      target: "aws_cloudfront_distribution.cdn" },
    { source: "aws_route53_record.apex",                     target: "aws_route53_zone.main" },
    { source: "aws_route53_record.apex",                     target: "aws_cloudfront_distribution.cdn" },
  ],
};
