import {
  ChangeAction,
  CloudProvider,
  ResourceLayer,
  type GraphModel,
} from "@terraform-viz/graph-schema";

/**
 * Serverless API upgrade plan.
 * Existing stack gets new capabilities (CREATE), tuning changes (UPDATE),
 * one legacy handler retired (DELETE), and stable resources left alone (NO_OP).
 * 14 resources across compute, database, and data layers.
 */
export const SERVERLESS_API: GraphModel = {
  id: "example-serverless-api",
  terraformVersion: "1.7.5",
  createdAt: "2026-04-24T10:00:00.000Z",
  nodes: [
    {
      id: "aws_iam_role.lambda_exec",
      address: "aws_iam_role.lambda_exec",
      type: "aws_iam_role",
      name: "lambda_exec",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: { name: "lambda-execution-role" },
    },
    {
      id: "aws_apigatewayv2_api.api",
      address: "aws_apigatewayv2_api.api",
      type: "aws_apigatewayv2_api",
      name: "api",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        name: "user-api",
        protocol_type: "HTTP",
        cors_configuration: {
          allow_origins: ["https://app.example.com"],
          allow_methods: ["GET", "POST", "PUT", "DELETE"],
        },
        tags: { Env: "prod", Team: "backend", Project: "user-api" },
      },
    },
    {
      id: "aws_apigatewayv2_stage.prod",
      address: "aws_apigatewayv2_stage.prod",
      type: "aws_apigatewayv2_stage",
      name: "prod",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: {
        name: "$default",
        auto_deploy: true,
        default_route_settings: { throttling_burst_limit: 100, throttling_rate_limit: 50 },
      },
    },
    {
      id: "aws_lambda_function.get_user",
      address: "aws_lambda_function.get_user",
      type: "aws_lambda_function",
      name: "get_user",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        function_name: "user-api-get-user",
        runtime: "nodejs20.x",
        handler: "index.handler",
        memory_size: 128,
        timeout: 10,
        tags: { Env: "prod", Team: "backend", Project: "user-api" },
      },
    },
    {
      id: "aws_lambda_function.create_user",
      address: "aws_lambda_function.create_user",
      type: "aws_lambda_function",
      name: "create_user",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        function_name: "user-api-create-user",
        runtime: "nodejs20.x",
        handler: "index.handler",
        memory_size: 256,
        timeout: 15,
        tags: { Env: "prod", Team: "backend", Project: "user-api" },
      },
    },
    {
      id: "aws_lambda_function.legacy_handler",
      address: "aws_lambda_function.legacy_handler",
      type: "aws_lambda_function",
      name: "legacy_handler",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.DELETE,
      moduleAddress: null,
      attributes: {
        function_name: "user-api-legacy",
        runtime: "nodejs14.x",
        handler: "app.handler",
        memory_size: 512,
        timeout: 30,
        tags: { Env: "prod", Team: "legacy", Project: "user-api" },
      },
    },
    {
      id: "aws_lambda_function.process_events",
      address: "aws_lambda_function.process_events",
      type: "aws_lambda_function",
      name: "process_events",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.COMPUTE,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: {
        function_name: "user-api-process-events",
        runtime: "nodejs20.x",
        memory_size: 512,
        timeout: 60,
        reserved_concurrent_executions: 10,
        tags: { Env: "prod", Team: "backend", Project: "user-api" },
      },
    },
    {
      id: "aws_dynamodb_table.users",
      address: "aws_dynamodb_table.users",
      type: "aws_dynamodb_table",
      name: "users",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        name: "users",
        billing_mode: "PAY_PER_REQUEST",
        hash_key: "userId",
        point_in_time_recovery: { enabled: true },
        tags: { Env: "prod", Team: "data", Project: "user-api" },
      },
    },
    {
      id: "aws_dynamodb_table.events",
      address: "aws_dynamodb_table.events",
      type: "aws_dynamodb_table",
      name: "events",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATABASE,
      changeAction: ChangeAction.NO_OP,
      moduleAddress: null,
      attributes: {
        name: "events",
        billing_mode: "PAY_PER_REQUEST",
        hash_key: "eventId",
        range_key: "timestamp",
        ttl: { attribute_name: "expiresAt", enabled: true },
        tags: { Env: "prod", Team: "data", Project: "user-api" },
      },
    },
    {
      id: "aws_sqs_queue.event_queue",
      address: "aws_sqs_queue.event_queue",
      type: "aws_sqs_queue",
      name: "event_queue",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: {
        name: "user-events",
        visibility_timeout_seconds: 30,
        message_retention_seconds: 345600,
        receive_wait_time_seconds: 20,
      },
    },
    {
      id: "aws_sqs_queue.dlq",
      address: "aws_sqs_queue.dlq",
      type: "aws_sqs_queue",
      name: "dlq",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "user-events-dlq", message_retention_seconds: 1209600 },
    },
    {
      id: "aws_lambda_event_source_mapping.sqs_trigger",
      address: "aws_lambda_event_source_mapping.sqs_trigger",
      type: "aws_lambda_event_source_mapping",
      name: "sqs_trigger",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { batch_size: 10, maximum_batching_window_in_seconds: 5 },
    },
    {
      id: "aws_sns_topic.notifications",
      address: "aws_sns_topic.notifications",
      type: "aws_sns_topic",
      name: "notifications",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.UPDATE,
      moduleAddress: null,
      attributes: { name: "user-notifications", kms_master_key_id: "alias/aws/sns" },
    },
    {
      id: "aws_cloudwatch_log_group.api",
      address: "aws_cloudwatch_log_group.api",
      type: "aws_cloudwatch_log_group",
      name: "api",
      provider: CloudProvider.AWS,
      layer: ResourceLayer.DATA,
      changeAction: ChangeAction.CREATE,
      moduleAddress: null,
      attributes: { name: "/aws/lambda/user-api", retention_in_days: 30 },
    },
  ],
  edges: [
    { source: "aws_apigatewayv2_stage.prod",               target: "aws_apigatewayv2_api.api" },
    { source: "aws_lambda_function.get_user",              target: "aws_iam_role.lambda_exec" },
    { source: "aws_lambda_function.create_user",           target: "aws_iam_role.lambda_exec" },
    { source: "aws_lambda_function.legacy_handler",        target: "aws_iam_role.lambda_exec" },
    { source: "aws_lambda_function.process_events",        target: "aws_iam_role.lambda_exec" },
    { source: "aws_lambda_event_source_mapping.sqs_trigger", target: "aws_sqs_queue.event_queue" },
    { source: "aws_lambda_event_source_mapping.sqs_trigger", target: "aws_lambda_function.process_events" },
  ],
};
